[metadata.heroku]
  root-package = "github.com/rheinardkorf/tide-slack"
  go-version = "1.10.3"
  install = [ "./..." ]

[[constraint]]
  branch = "master"
  name = "github.com/heroku/x"

[prune]
  go-tests = true
  unused-packages = true
